In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import openpyxl

In [2]:
path = r'C:\Users\Lenovo\Documents\GitHub\FMCG-Sales-PVM-Analytics\data\schema\fact_orders.csv'
df = pd.read_csv(path,sep=';',quotechar='"')

In [3]:
df

,order_id,unique_order_no,order_date,ship_date,ship_mode,sales,quantity,profit,Pack,return_id,product_id,customer_id,order_key,ship_key,location_id
0,1,CA-2019-100041,2019-11-20,2019-11-25,Standard Class,4.910,1,2.3077,Low,1,630,78,2019-11-20,2019-11-25,89
1,2,CA-2019-100041,2019-11-20,2019-11-25,Standard Class,314.550,3,150.9840,Low,1,1016,78,2019-11-20,2019-11-25,89
2,3,CA-2019-100041,2019-11-20,2019-11-25,Standard Class,9.080,2,4.0860,Low,1,1081,78,2019-11-20,2019-11-25,89
3,4,CA-2019-100083,2019-11-24,2019-11-29,Standard Class,24.784,1,7.7450,Low,2,1001,138,2019-11-24,2019-11-29,289
4,5,CA-2019-100153,2019-12-13,2019-12-17,Standard Class,63.880,4,24.9132,Low,3,1463,421,2019-12-13,2019-12-17,333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7258,7259,US-2020-169551,2020-07-07,2020-07-09,First Class,13.392,3,1.0044,Low,3315,1376,631,2020-07-07,2020-07-09,371
7259,7260,US-2020-169551,2020-07-07,2020-07-09,First Class,15.552,3,5.4432,Low,3315,1214,631,2020-07-07,2020-07-09,371
7260,7261,US-2020-169551,2020-07-07,2020-07-09,First Class,13.392,3,1.0044,Low,3316,1376,631,2020-07-07,2020-07-09,371
7261,7262,US-2020-169551,2020-07-07,2020-07-09,First Class,527.920,2,85.7870,Low,3315,1501,631,2020-07-07,2020-07-09,371
7262,7263,US-2020-169551,2020-07-07,2020-07-09,First Class,683.988,2,-113.9980,Low,3316,1650,631,2020-07-07,2020-07-09,371

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7263 entries, 0 to 7262
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         7263 non-null   int64
 1   unique_order_no  7263 non-null   object
 2   order_date       7263 non-null   object
 3   ship_date        7263 non-null   object
 4   ship_mode        7263 non-null   object
 5   sales            7263 non-null   float64
 6   quantity         7263 non-null   int64
 7   profit           7263 non-null   float64
 8   Pack             7263 non-null   object
 9   return_id        7263 non-null   int64
 10  product_id       7263 non-null   int64
 11  customer_id      7263 non-null   int64
 12  order_key        7263 non-null   object
 13  ship_key         7239 non-null   object
 14  location_id      7263 non-null   int64
dtypes: float64(2), int64(6), object(7)
memory usage: 851.3+ KB

In [5]:
df['unit_price'] = df['sales']/df['quantity'].round(2)
df['COGS_per_unit'] = 0.6*df['unit_price']
df['total_COGS'] = df['COGS_per_unit']*df['quantity']
df['gross_margin'] = df['sales']-df['COGS_per_unit']
df['gross_margin_per'] = df['gross_margin']*100/df['sales']

In [6]:
df

,order_id,unique_order_no,order_date,ship_date,ship_mode,sales,quantity,profit,Pack,return_id,product_id,customer_id,order_key,ship_key,location_id,unit_price,COGS_per_unit,total_COGS,gross_margin,gross_margin_per
0,1,CA-2019-100041,2019-11-20,2019-11-25,Standard Class,4.910,1,2.3077,Low,1,630,78,2019-11-20,2019-11-25,89,4.910,2.9460,2.9460,1.9640,40.0
1,2,CA-2019-100041,2019-11-20,2019-11-25,Standard Class,314.550,3,150.9840,Low,1,1016,78,2019-11-20,2019-11-25,89,104.850,62.9100,188.7300,251.6400,80.0
2,3,CA-2019-100041,2019-11-20,2019-11-25,Standard Class,9.080,2,4.0860,Low,1,1081,78,2019-11-20,2019-11-25,89,4.540,2.7240,5.4480,6.3560,70.0
3,4,CA-2019-100083,2019-11-24,2019-11-29,Standard Class,24.784,1,7.7450,Low,2,1001,138,2019-11-24,2019-11-29,289,24.784,14.8704,14.8704,9.9136,40.0
4,5,CA-2019-100153,2019-12-13,2019-12-17,Standard Class,63.880,4,24.9132,Low,3,1463,421,2019-12-13,2019-12-17,333,15.970,9.5820,38.3280,54.2980,85.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7258,7259,US-2020-169551,2020-07-07,2020-07-09,First Class,13.392,3,1.0044,Low,3315,1376,631,2020-07-07,2020-07-09,371,4.464,2.6784,8.0352,10.7136,80.0
7259,7260,US-2020-169551,2020-07-07,2020-07-09,First Class,15.552,3,5.4432,Low,3315,1214,631,2020-07-07,2020-07-09,371,5.184,3.1104,9.3312,12.4416,80.0
7260,7261,US-2020-169551,2020-07-07,2020-07-09,First Class,13.392,3,1.0044,Low,3316,1376,631,2020-07-07,2020-07-09,371,4.464,2.6784,8.0352,10.7136,80.0
7261,7262,US-2020-169551,2020-07-07,2020-07-09,First Class,527.920,2,85.7870,Low,3315,1501,631,2020-07-07,2020-07-09,371,263.960,158.3760,316.7520,369.5440,70.0
7262,7263,US-2020-169551,2020-07-07,2020-07-09,First Class,683.988,2,-113.9980,Low,3316,1650,631,2020-07-07,2020-07-09,371,341.994,205.1964,410.3928,478.7916,70.0

# Time peiod and PVM Analysis

In [7]:
#time period comparison setup
path_date = r'C:\Users\Lenovo\Documents\GitHub\FMCG-Sales-PVM-Analytics\data\schema\dim_date.csv'
df_date = pd.read_csv(path_date,sep=';',quotechar='"')
df_date

,date_key,full_date,yr,quarter_of_yr,mon_of_yr,month_name,day_of_year,week_of_year,is_weekend,day_of_week,day_name,month_year,yr_month
0,20190102,2019-01-02,2019,Q4,1,January,2,0,0,4,Wednesday,Jan-2019,2019-01
1,20190103,2019-01-03,2019,Q4,1,January,3,0,0,5,Thursday,Jan-2019,2019-01
2,20190104,2019-01-04,2019,Q4,1,January,4,0,0,6,Friday,Jan-2019,2019-01
3,20190105,2019-01-05,2019,Q4,1,January,5,0,1,7,Saturday,Jan-2019,2019-01
4,20190106,2019-01-06,2019,Q4,1,January,6,1,1,1,Sunday,Jan-2019,2019-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,20201228,2020-12-28,2020,Q3,12,December,28,52,0,2,Monday,Dec-2020,2020-12
727,20201229,2020-12-29,2020,Q3,12,December,29,52,0,3,Tuesday,Dec-2020,2020-12
728,20201230,2020-12-30,2020,Q3,12,December,30,52,0,4,Wednesday,Dec-2020,2020-12
729,20201231,2020-12-31,2020,Q3,12,December,31,52,0,5,Thursday,Dec-2020,2020-12
730,20210101,2021-01-01,2021,Q4,1,January,1,0,0,6,Friday,Jan-2021,2021-01

In [8]:
years = sorted(df_date['yr'].unique())
years

[np.int64(2019), np.int64(2020), np.int64(2021)]

In [ ]:
df['order_date'] = pd.to_datetime(df['order_date'])
df['ship_date'] = pd.to_datetime(df['ship_date'])
pvm_result  = []

for yr in years[1:]:
    base_yr = df[df['order_date'].dt.year==yr-1]
    current_yr = df[df['order_date'].dt.year==yr]

    #Calculation at SKU level
    base_agg = base_yr.groupby('product_id').agg(base_qty=('quantity','sum'),base_sales=('sales','sum'),base_cogs=('total_COGS','sum')).reset_index()
    curr_agg = current_yr.groupby('product_id').agg(curr_qty=('quantity','sum'),curr_sales=('sales','sum'),curr_cogs=('total_COGS','sum')).reset_index()

    pvm = pd.merge(base_agg,curr_agg,on='product_id',how='outer').fillna(0)

    pvm['base_price'] = pvm['base_sales']/pvm['base_qty']
    pvm['curr_price'] = pvm['curr_sales']/pvm['curr_qty']
    pvm = pvm.replace([float('inf'),-float('inf')],0).fillna(0)

    #Impacts
    price_impact = (pvm['base_qty']*(pvm['curr_price']-pvm['base_price'])).sum()
    vol_impact = (pvm['base_price']*(pvm['curr_qty']-pvm['base_qty'])).sum()
    mix = ((pvm['base_qty']-pvm['curr_qty'])*(pvm['base_price']-pvm['curr_price'])).sum()
    cost = -(pvm['base_cogs']-pvm['curr_cogs']).sum()


    pvm_result.append({
        'year' : yr,
        'base_margin' : (pvm['base_sales'] - pvm['base_cogs']).sum(),
        'price_impact' : price_impact,
        'volume_impact' : vol_impact,
        'mix' : mix,
        'cost' : cost,
        'total_margin_change' : price_impact+vol_impact+mix+cost,
        'current_margin' : (pvm['curr_sales'] - pvm['curr_cogs']).sum()
    })

2020 : 897026.0852
2020 : 538215.65112
2021 : 0.0
2021 : 0.0

In [10]:
pvm_summary = pd.DataFrame(pvm_result)
pvm_summary

,year,base_margin,price_impact,volume_impact,mix,cost,total_margin_change,current_margin
0,2020,294206.56504,-149932.839357,223.859148,311218.652809,96905.80356,2.584155e+05,358810.43408
1,2021,358810.43408,-897026.085200,-897026.085200,897026.085200,-538215.65112,-1.435242e+06,0.00000

In [11]:
pvm_summary_transposed = pvm_summary.transpose()
pvm_summary_transposed

                                 0             1
year                   2020.000000  2.021000e+03
base_margin          294206.565040  3.588104e+05
price_impact        -149932.839357 -8.970261e+05
volume_impact           223.859148 -8.970261e+05
mix                  311218.652809  8.970261e+05
cost                  96905.803560 -5.382157e+05
total_margin_change  258415.476160 -1.435242e+06
current_margin       358810.434080  0.000000e+00

In [12]:
pvm_summary_transposed.reset_index(inplace=True)
pvm_summary_transposed.rename(columns={'index':'Step'},inplace=True)

In [13]:
df_melted = pvm_summary_transposed.melt(id_vars='Step',var_name='Year',value_name='Value')
df_melted

                   Step Year         Value
0                  year    0  2.020000e+03
1           base_margin    0  2.942066e+05
2          price_impact    0 -1.499328e+05
3         volume_impact    0  2.238591e+02
4                   mix    0  3.112187e+05
5                  cost    0  9.690580e+04
6   total_margin_change    0  2.584155e+05
7        current_margin    0  3.588104e+05
8                  year    1  2.021000e+03
9           base_margin    1  3.588104e+05
10         price_impact    1 -8.970261e+05
11        volume_impact    1 -8.970261e+05
12                  mix    1  8.970261e+05
13                 cost    1 -5.382157e+05
14  total_margin_change    1 -1.435242e+06
15       current_margin    1  0.000000e+00

In [14]:
step_map = {
    'base_margin' : 'Base Margin',
    'price_impact' : 'Price Impact',
    'volume_impact' : 'Volume Impact',
    'mix' : 'Mix Impact',
    'cost' : 'Cost Impact',
    'total_margin_change' : 'Total Margin Change',
    'current_margin' : 'Current Margin'
}

df_melted['Step'] = df_melted['Step'].map(step_map)

In [15]:
order_map = {
    'Base Margin': 1,
    'Price Impact': 2,
    'Volume Impact': 3,
    'Mix Impact': 4,
    'Cost Impact': 5,
    'Total Margin Change' : 6,
    'Current Margin': 7
}

df_melted['Order'] = df_melted['Step'].map(order_map)

In [16]:
df_melted = df_melted[~df_melted['Step'].isnull()]

In [17]:
df_melted

                   Step Year         Value  Order
1           Base Margin    0  2.942066e+05    1.0
2          Price Impact    0 -1.499328e+05    2.0
3         Volume Impact    0  2.238591e+02    3.0
4            Mix Impact    0  3.112187e+05    4.0
5           Cost Impact    0  9.690580e+04    5.0
6   Total Margin Change    0  2.584155e+05    6.0
7        Current Margin    0  3.588104e+05    7.0
9           Base Margin    1  3.588104e+05    1.0
10         Price Impact    1 -8.970261e+05    2.0
11        Volume Impact    1 -8.970261e+05    3.0
12           Mix Impact    1  8.970261e+05    4.0
13          Cost Impact    1 -5.382157e+05    5.0
14  Total Margin Change    1 -1.435242e+06    6.0
15       Current Margin    1  0.000000e+00    7.0

In [18]:
df_melted['Year'] = df_melted['Year'].replace({0:2020,1:2021})
df_melted

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5876\1914143516.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_melted['Year'] = df_melted['Year'].replace({0:2020,1:2021})
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5876\1914143516.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_melted['Year'] = df_melted['Year'].replace({0:2020,1:2021})

                   Step  Year         Value  Order
1           Base Margin  2020  2.942066e+05    1.0
2          Price Impact  2020 -1.499328e+05    2.0
3         Volume Impact  2020  2.238591e+02    3.0
4            Mix Impact  2020  3.112187e+05    4.0
5           Cost Impact  2020  9.690580e+04    5.0
6   Total Margin Change  2020  2.584155e+05    6.0
7        Current Margin  2020  3.588104e+05    7.0
9           Base Margin  2021  3.588104e+05    1.0
10         Price Impact  2021 -8.970261e+05    2.0
11        Volume Impact  2021 -8.970261e+05    3.0
12           Mix Impact  2021  8.970261e+05    4.0
13          Cost Impact  2021 -5.382157e+05    5.0
14  Total Margin Change  2021 -1.435242e+06    6.0
15       Current Margin  2021  0.000000e+00    7.0

In [25]:
df_melted.to_excel(r"C:\Users\Lenovo\Desktop\pvm_waterfall_final.xlsx",index=False)

In [ ]:
from sqlalchemy import create_engine,text
from sqlalchemy import URL

url = URL.create(
    drivername='mysql+pymysql',
    username='root',
    password='',
    host='localhost',
    port=3306,
    database='pvm_db'
)

engine = create_engine(url)

In [47]:
df_melted.to_sql('pvm_analysis',con=engine,if_exists='append',index=False)

14

In [49]:
df.to_sql('fact_orders',con=engine,if_exists='append',index=False)

7263